### ISSUE TITLE
Why only a varchar(20) id?

### ISSUE THREAD

**Issue by crazedVic** [erwang/DataObject#1]
I really like the simplicity and functionality of your ORM.
Having said that, most of my projects require the usual AUTO_INCREMENT INTEGER id field functionality, so at this point without modification I can't use it.
I am curious as to the thinking behind this design decision and any chance that you might support the traditional auto-incrementing integer id field in the future?

**Comment by erwang** [comment]
Hello, thks for your comment.
Using an autoincrement id is not a good idea, you can find a lot of posts in the weeb : 
- https://www.clever-cloud.com/blog/engineering/2015/05/20/why-auto-increment-is-a-terrible-idea/
- https://www.google.com/search?q=why+don't+use+autoicrement&ie=utf-8&oe=utf-8
I saw you added autoincrement in your fork, I'm going to add a new param to use autoincrement

**Comment by erwang** [comment]
Added a static attribute to param autoincrement in v1.0.4 on packagist.
