### ISSUE TITLE
Use of underscores in linking classes Book_Author not supported in some PHP?

### ISSUE THREAD

**Issue by crazedVic** [erwang/DataObject#2]
I'm using latest PHP and Composer, and Flight PHP.

class_exists($this->_getClassBetween($class, true)) line 400'ish always returns false for me for any class that has an underscore _ in the name.

I had to name my linking class BookAuthor and i had to change your code to remove the _ concatenation as follows; 
```
protected function _getClassBetween($class, $namespace = false)
    {
        $thisClass = $this->_getClass();
        $nsp = $this->_getNamespace();
        $array = [join('', array_slice(explode('\\', $class), -1)), join('', array_slice(explode('\\', $thisClass), -1))];
        sort($array);
        if ($namespace) {
            return $nsp . '\\' . implode('', $array);
        } else {
            return implode('', $array);
        }
    }

````

**Comment by erwang** [comment]
Added a static attribute to param class separator in v1.0.4 on packagist.
