### ISSUE TITLE
Should be FETCH_COLUMN not FETCH_ASSOC

### ISSUE THREAD

**Issue by crazedVic** [erwang/DataObject#3]
Trying to retrieve book->editor is broken because the check to see if the field is in the columns  in__get function currently always returns false;

`if (in_array($name . '_id', self::getColumns())) {`

The line:
 `return $q->fetchAll(\PDO::FETCH_ASSOC);`
on line 146 should read
`$result = $q->fetchAll(\PDO::FETCH_COLUMN);`

**Comment by crazedVic** [comment]
actually this ended up breaking stuff so i had to change it to this:
`if (in_array($name . '_id', self::getColumns(true))) {`
and the function is now like this:
```
public static function getColumns($asArray = false)
    {

        $table = self::getTable();

        $statement = 'SHOW COLUMNS FROM `' . $table . '`';
        try {
            $q = self::_getPdo()->prepare($statement);
            $q->execute();
            if ($asArray) {
                return $q->fetchAll(\PDO::FETCH_COLUMN);
            } else {
                return $q->fetchAll(\PDO::FETCH_ASSOC);
            }

        } catch (\Exception $e) {
            print($statement);
            exit($e->getMessage());
        }
    }
```

**Comment by erwang** [comment]
There was an error in _get, v1.0.4 correct this.
